### ISSUE TITLE
Uncaught TypeError: atom.workspace.toggle is not a function

### ISSUE THREAD

**Issue by qinglangee** [atom/active-editor-info#1]
I load the example and run the command, atom throws a error.
And below is the error report created by atom.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [active-editor-info](https://github.com/atom/active-editor-info) package 0.0.0

### Stack Trace

Uncaught TypeError: atom.workspace.toggle is not a function

```
At /home/zhch/temp/d3/active-editor-info/lib/active-editor-info.js:40

TypeError: atom.workspace.toggle is not a function
    at Object.toggle (/home/zhch/github/qinglangee/active-editor-info/lib/active-editor-info.js:40:20)
    at atom-workspace.activeEditorInfoToggle (/home/zhch/github/qinglangee/active-editor-info/lib/active-editor-info.js:21:49)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at Object.didConfirmSelection (/app.asar/node_modules/command-palette/lib/command-palette-view.js:106:29)
    at SelectListView.confirmSelection (/app.asar/node_modules/atom-select-list/src/select-list-view.js:301:20)
    at HTMLDivElement.coreConfirm (/app.asar/node_modules/atom-select-list/src/select-list-view.js:67:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:08.4.0 command-palette:toggle (input.hidden-input)
     -1:05.5.0 core:confirm (input.hidden-input)
     -1:05.1.0 active-editor-info:toggle (input.hidden-input)
```

### Non-Core Packages

```
active-editor-info 0.0.0 
custom-finder 0.0.0 
language-babel 2.67.0 
xiaoqiao-todo 0.0.0 
```

**Comment by qinglangee** [comment]
update atom to v1.19.0 fixed the problem.
